apiVersion: v2
name: mcp-dbstore
description: A Helm chart for deploying MCP DBStore server with PostgreSQL database
type: application
version: 0.1.0
appVersion: "0.0.1"
keywords:
  - mcp
  - model-context-protocol
  - database
  - fastmcp
  - llama-stack
home: https://github.com/rh-ai-kickstart/ai-architecture-charts
sources:
  - https://github.com/rh-ai-kickstart/ai-architecture-charts/tree/main/mcp-servers/store_db
maintainers:
  - name: AI Architecture Team
    email: team@ai-architecture
annotations:
  category: AI/ML Tools
dependencies: [] 