# options are [S3, GITHUB, URL]
source: S3
# embedding model to use for creating embeddings
embedding_model: all-MiniLM-L6-v2
# name of the vector db with version, pipeline will be created with pipeline_red_hat_openshift
name: "demo-rag-vector-db"
# version of the knowledgebase
version: "1.0"

S3:
  access_key_id: minio_rag_user
  secret_access_key: minio_rag_password
  bucket_name: documents
  endpoint_url: http://minio:9000
  region: us-east-1

GITHUB:
  url: https://github.com/
  path: /docs
  token: auth_token
  branch: ""

URL: 
  URLS: 
  - "https://arxiv.org/pdf/2408.09869"
  - "https://github.com/docling-project/docling/blob/main/tests/data/pdf/2206.01062.pdf"

